### ISSUE TITLE
embed.ly integration is not working

### ISSUE THREAD

**Issue by saitodisse** [jparyani/Telescope#6]
I cannot make embed.ly integration to work.
I am getting this error:

```
** Starting Meteor...
[AccountsTemplates] WARNING: showForgotPasswordLink set to true, but MAIL_URL is not configured!
Starting artwells:queue for Herald
{ [Error: getaddrinfo ENOTFOUND] stack: [Getter] }
Exception while invoking method 'getEmbedlyData' SyntaxError: Unexpected token N
    at Object.parse (native)
    at getEmbedlyData (packages/telescope-embedly/lib/server/get_embedly_data.js:36:1)
    at [object Object].Meteor.methods.getEmbedlyData (packages/telescope-embedly/lib/server/get_embedly_data.js:103:1)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:182:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
```

**Comment by jparyani** [comment]
embed.ly makes a server side call out over the internet. This will not work as-is inside Sandstorm for security reasons (see https://docs.sandstorm.io/en/latest/using/security-practices/#true-confinement).
